# Generated by Django 5.0.1 on 2026-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.FloatField(default=0),
        ),
    ]
